services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - AUTH_SERVICE_URI=${AUTH_SERVICE_URI}
      - USER_SERVICE_URI=${USER_SERVICE_URI}
      - TOUR_SERVICE_URI=${TOUR_SERVICE_URI}
      - BOOKING_SERVICE_URI=${BOOKING_SERVICE_URI}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - user-service
      - tour-service
      - booking-service

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "4002:4002"
    environment:
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - MONGO_URI=${MONGO_URI}

  tour-service:
    build: ./tour-service
    container_name: tour-service
    restart: always
    ports:
      - "4003:4003"
    environment:
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - MONGO_URI=${MONGO_URI}

  booking-service:
    build: ./booking-service
    container_name: booking-service
    restart: always
    ports:
      - "4004:4004"
    environment:
      - SECRET_KEY_ACCESS_TOKEN=${SECRET_KEY_ACCESS_TOKEN}
      - MONGO_URI=${MONGO_URI}